[package]
name = "logfire-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opentelemetry = "0.22.0"
#opentelemetry-stdout = { vesion = "0.3.0", features = ["trace"] }

opentelemetry_sdk = { version = "0.22.1", features = ["rt-tokio"] }
opentelemetry-http = { version = "0.11.0", features = ["reqwest"] }
opentelemetry-otlp = { vesion = "0.15.0", features = ["trace", "http-proto"] }
reqwest = { version = "0.11.27" }
tokio = { version = "1", features = ["full"] }
